class CreatePlants < ActiveRecord::Migration
  def self.up
    create_table :plants do |t|
      t.string :AcceptedSymbol
      t.string :SynonymSymbol
      t.string :ScientificName
      t.string :Symbol
      t.string :CommonName
      t.text :PLANTS_Floristic_Area
      t.text :State
      t.string :Category
      t.string :Genus
      t.string :Family
      t.string :FamilySymbol
      t.string :FamilyCommonName
      t.string :xOrder
      t.string :SubClass
      t.string :Class
      t.string :SubDivision
      t.string :Division
      t.string :SuperDivision
      t.string :SubKingdom
      t.string :Kingdom
      t.integer :ITIS_TSN
      t.string :Duration
      t.string :GrowthHabit
      t.string :NativeStatus
      t.string :FederalNoxiousStatus
      t.string :FederalNoxiousCommonName
      t.text :StateNoxiousStatus
      t.text :StateNoxiousCommonName
      t.string :Invasive
      t.string :Federal_TE_Status
      t.string :State_TE_Status
      t.text :State_TE_Common_Name
      t.string :NationalWetlandIndicatorStatus
      t.string :RegionalWetlandIndicatorStatus
      t.string :ActiveGrowthPeriod
      t.string :AfterHarvestRegrowthRate
      t.string :Bloat
      t.string :C2N_Ratio
      t.string :CoppicePotential
      t.string :FallConspicuous
      t.string :FireResistance
      t.string :FlowerColor
      t.string :FlowerConspicuous
      t.string :FoliageColor
      t.string :FoliagePorositySummer
      t.string :FoliagePorosityWinter
      t.string :FoliageTexture
      t.string :FruitColor
      t.string :FruitConspicuous
      t.string :GrowthForm
      t.string :GrowthRate
      t.integer :MaxHeight20Yrs
      t.integer :MatureHeight
      t.string :KnownAllelopath
      t.string :LeafRetention
      t.string :Lifespan
      t.string :LowGrowingGrass
      t.string :NitrogenFixation
      t.string :ResproutAbility
      t.string :Shape_and_Orientation
      t.string :Toxicity
      t.string :AdaptedCoarseSoils
      t.string :AdaptedMediumSoils
      t.string :AdaptedFineSoils
      t.string :AnaerobicTolerance
      t.string :CaCO3Tolerance
      t.string :ColdStratification
      t.string :DroughtTolerance
      t.string :FertilityRequirement
      t.string :FireTolerance
      t.integer :MinFrostFreeDays
      t.string :HedgeTolerance
      t.string :MoistureUse
      t.decimal :pH_Minimum
      t.decimal :pH_Maximum
      t.integer :Min_PlantingDensity
      t.integer :Max_PlantingDensity
      t.integer :Precipitation_Minimum
      t.integer :Precipitation_Maximum
      t.integer :RootDepthMinimum
      t.string :SalinityTolerance
      t.string :ShadeTolerance
      t.integer :TemperatureMinimum
      t.string :BloomPeriod
      t.string :CommercialAvailability
      t.string :FruitSeedAbundance
      t.string :FruitSeedPeriodBegin
      t.string :FruitSeedPeriodEnd
      t.string :FruitSeedPersistence
      t.string :Propogated_by_BareRoot
      t.string :Propogated_by_Bulbs
      t.string :Propogated_by_Container
      t.string :Propogated_by_Corms
      t.string :Propogated_by_Cuttings
      t.string :Propogated_by_Seed
      t.string :Propogated_by_Sod
      t.string :Propogated_by_Sprigs
      t.string :Propogated_by_Tubers
      t.integer :Seeds_per_Pound
      t.string :SeedSpreadRate
      t.string :SeedlingVigor
      t.string :SmallGrain
      t.string :VegetativeSpreadRate
      t.string :Berry_Nut_Seed_Product
      t.string :ChristmasTreeProduct
      t.string :FodderProduct
      t.string :FuelwoodProduct
      t.string :LumberProduct
      t.string :NavalStoreProduct
      t.string :NurseryStockProduct
      t.string :PalatableBrowseAnimal
      t.string :PalatableGrazeAnimal
      t.string :PalatableHuman
      t.string :PostProduct
      t.string :ProteinPotential
      t.string :PulpwoodProduct
      t.string :VeneerProduct

      t.timestamps
    end
  end

  def self.down
    drop_table :plants
  end
end
